name: Feature Request
description: Request a feature that you would like to see implemented in the project.
labels: [enhancement]

body:
- type: markdown
  attributes:
    value: |
      - Check if the feature was already requested.
      - Include only one feature per issue.

- type: textarea
  attributes:
    label: Feature Description
    description: Please describe the feature as detailed as possible. Feel free to include examples.
  validations:
    required: true
